create table if not exists public.produccion_agregados_cuncia (
  id bigint generated by default as identity not null,
  id_registro text not null,
  fecha date null,
  planta text null,
  canaveral numeric(10, 2) null default 0.00,
  guayuriba numeric(10, 2) null default 0.00,
  linea_3 numeric(10, 2) null default 0.00,
  total_m3 numeric(10, 2) null default 0.00,
  m3_proyectado numeric(10, 2) null default 0.00,
  diferencia numeric(10, 2) null default 0.00,
  porcentaje_cumplimiento numeric(10, 2) null default 0.00,
  observacion text null,
  agregados text null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint produccion_agregados_cuncia_pkey primary key (id),
  constraint id_registro_fecha_unico_cuncia unique (id_registro, fecha)
) TABLESPACE pg_default;

create index if not exists idx_prod_agregados_cuncia_id_reg on public.produccion_agregados_cuncia using btree (id_registro) TABLESPACE pg_default;

create index if not exists idx_prod_agregados_cuncia_reg_fecha on public.produccion_agregados_cuncia using btree (id_registro, fecha) TABLESPACE pg_default;
